### PR TITLE
base: lmp-staging: k3: switch mcdepends from do_image_complete

### PR DESCRIPTION
**Pull request by ricardosalveti**
Follow meta-ti 9b4f5af61 and switch mcdepends from do_image_complete to do_image.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
This is to allow us to move meta-ti to https://github.com/lmp-mirrors/meta-ti/commit/c3916324a01fe96c68a78ef9ed0070d6b1fc8f2f.

**Review by MrCry0 — APPROVED** [review]

**Comment by ricardosalveti** [comment]
This meta-ti rev is not booting correctly on am64, so will hold this pr for now.

**Comment by ricardosalveti** [comment]
Was actually just a bad sdcard.

**Comment by quaresmajose** [comment]
> Was actually just a bad sdcard.

nice, we can now bump to latest meta-ti rev using https://github.com/foundriesio/meta-lmp/pull/1345

**Pull request merged**
