### PR TITLE
Update container stack to the latest possible on kirkstone

### PR DESCRIPTION
**Pull request by ricardosalveti**
* base: runc-opencontainers: update to 1.1.4
* base: containerd-opencontainers: update to 1.6.9
* base: docker-ce: update to 20.10.21
* base: docker-compose: update to v2.10.2

We can't update docker-compose to the latest v2.12 as it requires golang 1.19, and we're still using 1.17.

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by mike-sul** [comment]
@ricardosalveti Can we update `nerdctl` too, or we don't control its version explicitly only via `meta-virtualization`?

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
> @ricardosalveti Can we update `nerdctl` too, or we don't control its version explicitly only via `meta-virtualization`?

We can update it as well, let me have a look.

**Comment by ricardosalveti** [comment]
@mike-sul updated to the latest from current meta-virtualization, which is version 0.22.2 (not the latest but updating to the latest will require a bit of effort due the way the recipe was created).

Updated your patches but only build tested it, mind giving it a shot? Thanks!

**Comment by mike-sul** [comment]
> Updated your patches but only build tested it, mind giving it a shot? Thanks!

It works for me. `aklite` works as expected if it uses nerdctl v0.22.2 instead of `docker compose`. 
```
root@intel-corei7-64:/var/sota# nerdctl --version
nerdctl version 0.22.2-2-ge084a2d.m
```

```
root@intel-corei7-64:/var/sota# nerdctl ps 
CONTAINER ID    IMAGE                                                                                                     COMMAND                   CREATED           STATUS    PORTS                     NAMES
04d7dbf76003    docker.io/foundries/shellhttpd@sha256:bb95a5e0547f8834a6356b019ffe7e71c87f19a0a219e206cf8340a3d587011a    "/usr/local/bin/http…"    49 seconds ago    Up        0.0.0.0:8080->8080/tcp    simpleapp_httpd_1
```

**Review by mike-sul — APPROVED** [review]

**Comment by ricardosalveti** [comment]
Nice, thanks! Will merge so we start testing the update.

**Pull request merged**
