### PR TITLE
Additional fixes for the NXP BSP

### PR DESCRIPTION
**Pull request by ricardosalveti**
* Bump linux-firmware imx to be aligned with current BSP release
* Fix kernel entrypoint for mx8mm
* Add bluetooth support for imx8mmevka
* Add qca firmware on imx8mm devices (for evka)

### CODE REVIEW

**Comment by quaresmajose** [comment]
commit https://github.com/foundriesio/meta-lmp/pull/886/commits/9cd07f3b49595e3cb3dd928e3dc461e31d9b2d40 says `MACHINE_FEATURES` but the code change `MACHINE_FIRMWARE`

**Comment by ricardosalveti** [comment]
> commit [9cd07f3](https://github.com/foundriesio/meta-lmp/commit/9cd07f3b49595e3cb3dd928e3dc461e31d9b2d40) says `MACHINE_FEATURES` but the code change `MACHINE_FIRMWARE`

Fixed, thanks!

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by quaresmajose — APPROVED** [review]
LGTM

**Pull request merged**
