### PR TITLE
base: openssl: refresh patch to the backported version

### PR DESCRIPTION
**Pull request by ricardosalveti**
Update the patch in order to be aligned with what was merged in the end.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Pending test on x86/kria.

**Review by quaresmajose — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
Tested on intel.

**Pull request merged**
