### PR TITLE
bsp: Add mfgtool files for create fuse and close script for imx6ullevk

### PR DESCRIPTION
**Pull request by Tim-Anderson**
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
@Tim-Anderson @ricardosalveti I wonder if these scripts wouldn't be better landed in `lmp-tools`

**Comment by mike-scott** [comment]
Ah.. NM, I see they are kind of hard-coded to imx6ullevk:
```
SDP: boot -f SPL-mfgtool.signed -dcdaddr 0x0907000 -cleardcd
```

**Comment by ricardosalveti** [comment]
> @Tim-Anderson @ricardosalveti I wonder if these scripts wouldn't be better landed in `lmp-tools`

I think it is probably better to land at lmp-tools because the flow is a bit confusing, as you use the script to generate another script that should then be also provided via mfgtools by default.

We can have a soc family specific folder at https://github.com/foundriesio/lmp-tools/tree/master/security/imx_hab4.

**Comment by Tim-Anderson** [comment]
I understand what you are saying. and I am okay with that as long as we do
not put actual fuse and close scripts in the mfgtool build then.

**Comment by ricardosalveti** [comment]
> I understand what you are saying. and I am okay with that as long as we do not put actual fuse and close scripts in the mfgtool build then.

Yup, I think the expected flow would be for our customer to use the scripts from lmp-tools and then include as part of meta-subscriber-overrides.

**Comment by Tim-Anderson** [comment]
Moving to lmp-tools

**Pull request closed without merging**
