### PR TITLE
bsp: u-boot config to enable secondary boot on imx7ulpea-ucom

### PR DESCRIPTION
**Pull request by Tim-Anderson**
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Please just change the commit description as these changes are specific to the imx7ulpea-ucom target, and not generic to imx7/imx7ulp.

**Review by igoropaniuk — APPROVED** [review]
LGTM

**Review by igoropaniuk — CHANGES_REQUESTED** [review]
```
CONFIG_FSL_FASTBOOT_BOOTLOADER_SECONDARY=y
```

should be added for mfgtool lmp config

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
