### PR TITLE
meta-lmp: updates for kernel 5.0 and RISC-V

### PR DESCRIPTION
**Pull request by mike-scott**
- kernel update to 5.0.6
- boot scripts to support u-boot for qemuriscv64
- remove riscv-pk append (bbl is dead)
- opensbi build fix
- lmp-mini-image add more room for OTA update
- lmp-machine move qemuriscv64 target to opensbi/u-boot support (with fitImage for Linux)

### CODE REVIEW

**Comment by mike-scott** [comment]
Uses lmp-kernel-cache here: https://github.com/foundriesio/lmp-kernel-cache/commits/linux-v5.0.y

**Comment by mike-scott** [comment]
Requires OE-core patch: https://patchwork.openembedded.org/patch/160391/

**Comment by mike-scott** [comment]
Requires meta-riscv layer update: https://github.com/foundriesio/lmp-manifest/pull/16

**Comment by ricardosalveti** [comment]
LGTM

**Pull request merged**
