### PR TITLE
base: initramfs-ostree-lmp-recovery: Fix image_download.sh URL

### PR DESCRIPTION
**Pull request by caiotpereira**
Add missing "lmp" to URL in image_download.sh

### CODE REVIEW

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
LGTM, please just fix the commit description.

Subject: 'base: ...."
Body: add your git sign-off-by (git commit -s --amend).

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by quaresmajose — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
