### PR TITLE
bsp: u-boot-xlnx: set CONFIG_SF_DEFAULT_SPEED to 40000000

### PR DESCRIPTION
**Pull request by ricardosalveti**
Set a higher default speed for a faster QSPI boot process.

uz3eg-iocc-sec boot.bin also updated to reflect the updated SPL.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]
@ricardosalveti Was this file `meta-lmp-bsp/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware/uz3eg-iocc-sec/boot.bin` added mistakenly?

**Review by MrCry0 — COMMENTED** [review]
@ricardosalveti Was this file meta-lmp-bsp/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware/uz3eg-iocc-sec/boot.bin added mistakenly?

**Comment by ricardosalveti** [comment]
@MrCry0 this is needed for uz sec as SPL is provided in binary form, so any change done to the u-boot config that affects SPL requires a boot.bin bump.

But one thing that I forgot is bumping the lmp-boot-firmware pr.

**Comment by ricardosalveti** [comment]
Updated and extended the commit message to cover boot.bin.

**Comment by ricardosalveti** [comment]
Will merge to get this included as part of the lmp-manifest update.

**Pull request merged**
