### PR TITLE
main: apalis-imx6: switch to op-tee 3.15

### PR DESCRIPTION
**Pull request by MrCry0**
- disable pta.rng 
-  bsp: apalis-imx6: switch to op-tee 3.15

### CODE REVIEW

**Comment by MrCry0** [comment]
@ricardosalveti with the https://github.com/foundriesio/u-boot/pull/143 OP-TEE works well on both `apalis-imx6` and `apalis-imx6-sec` images.
We can use soft rng instead until fixing the issue with `pta.rng`.

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by vanmaegima — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
@MrCry0 please add the u-boot bump as part of this pr.

**Comment by MrCry0** [comment]
> @MrCry0 please add the u-boot bump as part of this pr.

Done.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
