### PR TITLE
Drop toradex support from meta-lmp

### PR DESCRIPTION
**Pull request by mike-scott**
Series of commits to remove toradex machine support.

This support is being re-added in partner layer which can be updated according to the Toradex release schedule.

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]

**Review by MrCry0 — COMMENTED** [review]
@mike-scott I think the `meta-lmp-bsp/recipes-kernel/linux/linux-lmp_6.1.bbappend` could be removed as well

also, there are toradex-related settings in the `meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files_%.bbappend`

`meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-*` could be removed.

**Comment by angolini** [comment]
I might get confused with something, but it looks like a "bsp: u-boot-fio-mfgtool: apalis-imx**8**: move out toradex support" is missing?

**Comment by mike-scott** [comment]
Addressed @MrCry0 and @angolini comments and dropped more files related to Toradex HW.

NOTE: I combined the *-sec removals with their related MACHINE names.  It was confusing to see these broken out anyway.

**Review by ricardosalveti — APPROVED** [review]
LGTM, thanks for cleaning this up.

**Pull request merged**
