### PR TITLE
Added new base distros with wayland support

### PR DESCRIPTION
**Pull request by MaxPayne86**
Initial sanity check with

```
bitbake -e weston-init | awk '/^# \$SRC_URI \[/,/^SRC_URI/'
```

### CODE REVIEW

**Comment by quaresmajose** [comment]
LGTM, but I didn't understand very well the sanity check command on the PR description.

Thanks for the patch @MaxPayne86

**Comment by MaxPayne86** [comment]
> LGTM, but I didn't understand very well the sanity check command on the PR description.

Minor test to see if the files that are normally included in weston-init and lmp-wayland distro are applied also with this new distro. Before this command of course you need to do something like

```
DISTRO=lmp-base-xwayland MACHINE=<YOUR-MACHINE> . setup-environment
```

files I'm referring to below

```
SRC_URI:append:lmp-wayland = " \
    file://utilities-terminal.png \
    file://background.jpg \
    file://weston.env \
    file://weston.service.patch \
    file://tmpfiles.conf \
"
```

**Comment by quaresmajose** [comment]
Thanks for the explanation, i got it.
Recent versions of bitbake can do the same in a more elegant way:

```
bitbake-getvar -r weston-init SRC_URI
```

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
