### PR TITLE
bsp: u-boot-ostree-scr-fit: common: move fiovb var init

### PR DESCRIPTION
**Pull request by igoropaniuk**
Move initialization of fiovb vars obtained from RPMB.

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

### CODE REVIEW

**Comment by MrCry0** [comment]
@igoropaniuk I see the code moving has a purpose. Could you add this purpose to the commit message?

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Comment by igoropaniuk** [comment]
@MrCry0 fixed

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
