### PR TITLE
bsp: u-boot-fio: imx6ullevk: increase CONFIG_ENV_SIZE

### PR DESCRIPTION
**Pull request by igoropaniuk**
Set CONFIG_ENV_SIZE=0x4000 in lmp.cfg.

This fixes env size exceed error:
Saving Environment to FAT... Env export buffer too small: 8188, but need 8228

### CODE REVIEW

**Comment by quaresmajose** [comment]
Maybe this is also need in lmp-base?

**Comment by igoropaniuk** [comment]
@quaresmajose in lmp-base we don't use so big amount of env variables in boot.cmd script

**Review by quaresmajose — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
