### PR TITLE
Updates for 7ulp, aligning with EA 5.4-based BSP

### PR DESCRIPTION
**Pull request by ricardosalveti**
* Update kernel to the latest 5.4 based branch (forked from the EA BSP)
* Add support for lmp-base on imx7ulpea-ucom (to easy testing/development)

Boot tested on imx7ulpea-ucom, with and without OP-TEE.

This is to be used as a starting point for @vanmaegima.

### CODE REVIEW

**Comment by mike-scott** [comment]
@ricardosalveti We should probably move the mfgtool kernel to the 5.4 branch as well.
```
diff --git a/meta-lmp-bsp/conf/machine/include/lmp-mfgtool-machine-custom.inc b/meta-lmp-bsp/conf/machine/include/lmp-mfgtool-machine-custom.inc
index 319e9bb9..0a9291c2 100644
--- a/meta-lmp-bsp/conf/machine/include/lmp-mfgtool-machine-custom.inc
+++ b/meta-lmp-bsp/conf/machine/include/lmp-mfgtool-machine-custom.inc
@@ -5,8 +5,8 @@ PREFERRED_VERSION_u-boot-fio-mfgtool_imx ?= "2020.04"
 UBOOT_SIGN_ENABLE_imx7ulpea-ucom = "1"
 PREFERRED_PROVIDER_virtual/kernel_imx7ulpea-ucom = "linux-lmp-dev-mfgtool"
 KERNEL_REPO_imx7ulpea-ucom ?= "git://github.com/foundriesio/linux.git"
-LINUX_VERSION_imx7ulpea-ucom ?= "4.19.y"
-KERNEL_BRANCH_imx7ulpea-ucom ?= "linux-ea-v4.19.y"
+LINUX_VERSION_imx7ulpea-ucom ?= "5.4.47"
+KERNEL_BRANCH_imx7ulpea-ucom ?= "linux-ea-v5.4.y"
 PREFERRED_VERSION_optee-os-fio-mfgtool_imx7ulpea-ucom = "3.6.0+git"
 PREFERRED_PROVIDER_virtual/bootloader_imx7ulpea-ucom = "u-boot-fio-mfgtool"
 PREFERRED_PROVIDER_u-boot_imx7ulpea-ucom = "u-boot-fio-mfgtool"
```

**Comment by mike-scott** [comment]
Heh, and as I'm looking at this, I realize we need to drop:
```
PREFERRED_VERSION_optee-os-fio-mfgtool_imx7ulpea-ucom = "3.6.0+git"
```

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
24792 subtests of which 0 failed
105 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

Both lmp and mfgtools working correctly with latest kernel and optee.

**Review by mike-scott — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
question, did we remove the FIT_SEPERATOR token?

Anyway LGTM

**Review by vanmaegima — APPROVED** [review]

**Comment by mike-scott** [comment]
> question, did we remove the FIT_SEPERATOR token?
> 
> Anyway LGTM

We didn't need to change anything for the `FIT_NODE_SEPARATOR` setting due to `imx7ulpea-ucom` already using the "common" boot.cmd.  @ricardosalveti did fix the remaining `@` sign usage in the `full_image.uuu` script with this PR.

**Pull request merged**
