### PR TITLE
Optee os update to 3.20+fio (take 2)

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Follow up of https://github.com/foundriesio/meta-lmp/pull/1019 (as igor is off today and I needed to do a bit more testing due some other stuff).

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
30376 subtests of which 0 failed
128 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@imx8mq-evk:~#
```

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
30168 subtests of which 0 failed
128 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@imx6ulevk:~#
```

**Comment by ricardosalveti** [comment]
With SE050:
```
+-----------------------------------------------------
30469 subtests of which 0 failed
127 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@imx8mm-lpddr4-evk-sec:~#
```

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
31056 subtests of which 0 failed
128 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@qemuarm64-secureboot:~#
```

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
30342 subtests of which 0 failed
128 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@am64xx-evm:~#
```

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
30348 subtests of which 0 failed
128 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@kv260:~#
```

**Review by quaresmajose — APPROVED** [review]

**Review by MrCry0 — APPROVED** [review]
**UPDATE**

Tested with `main` lmp-manifest + 
```
<project name="meta-lmp" path="layers/meta-lmp" remote="ricardo" revision="optee"/>
```

```
30227 subtests of which 2 failed
128 test cases of which 1 failed
0 test cases were skipped
TEE test application done!
fio@imx6ullevk:~$ 
```

```
regression_1039.1 FAILED first error at /usr/src/debug/optee-test/3.20.0-r0/git/host/xtest/regression_1000.c:3206
regression_1039.2 FAILED first error at /usr/src/debug/optee-test/3.20.0-r0/git/host/xtest/regression_1000.c:3213
regression_1039 FAILED
```

**Comment by MrCry0** [comment]
```
+-----------------------------------------------------
30376 subtests of which 2 failed
128 test cases of which 1 failed
0 test cases were skipped
TEE test application done!
fio@apalis-imx8:~$ 
```

**Comment by MrCry0** [comment]
> That is weird, both failed the same way. Will try on my imx6ullevk-sec as well.

This is really weird and seems a factory cache issue.

The error is fixed in `optee_test` commit `c7f0b40 ("ta: makefile: add compilation of subkey TAs")`
```
* regression_1039 Test subkey verification
o E/LD:  init_elf:486 sys_open_ta_bin(a720ccbb-51da-417d-b82e-e5445d474a7a)
regression_1039.1 Load TA with two levels of subkeys
/usr/srcE/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000f
/debug/optee-test/3.20.0-r0/git/host/xtest/regression_1000.c:3206: xtest_teec_open_session(&session, &subkey1_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff000f = TEEC_ERRS
  regression_1039.1 FAILED
o regression_1039.2 Load TA with identity subkey
/usr/src/debug/optee-test/3.20.0-r0/git/host/xtest/regression_1000.c:3213: xtest_teec_open_session(&session, &subkey2_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff000f = S
  regression_1039.2 FAILED
  regression_1039 FAILED
```

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
30109 subtests of which 2 failed
128 test cases of which 1 failed
0 test cases were skipped
TEE test application done!
root@stm32mp15-disco:~#
```

CKR_HOST_MEMORY, and I don't get this failure on every run.

```
* pkcs11_1007 PKCS11: Check operations release at session closure
/usr/src/debug/optee-test/3.20.0-r0/git/host/xtest/pkcs11_1000.c:1491: rv has an unexpected value: 0x2 = CKR_HOST_MEMORY, expected 0x0 = CKR_OK
/usr/src/debug/optee-test/3.20.0-r0/git/host/xtest/pkcs11_1000.c:1539: rv has an unexpected value: 0x2 = CKR_HOST_MEMORY, expected 0x0 = CKR_OK
  pkcs11_1007 FAILED
```

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
3717 subtests of which 0 failed
27 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@stm32mp15-disco:~# xtest -t pkcs11
```

Just the pkcs11 tests work ok.

**Review by angolini — APPROVED** [review]

**Comment by ricardosalveti** [comment]
> CKR_HOST_MEMORY, and I don't get this failure on every run.

It fails when trying to allocate SHM memory for the test case, which is just a normal shm alloc operation, and why it works OK when retrying or when just running the pkcs11 tests.

@igoropaniuk is this something you faced as well? I'm ok merging even with this failure but we should investigate this one a bit more (not an issue for the normal scenario as we never really stress optee this way).

**Comment by ricardosalveti** [comment]
```
+-----------------------------------------------------
30227 subtests of which 0 failed
128 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@imx6ullevk-sec:~#
```

@MrCry0 working fine here.

**Comment by ricardosalveti** [comment]
Will merge so we get a wider testing on this (we can fix as needed).

**Comment by MrCry0** [comment]
> ```
> +-----------------------------------------------------
> 30227 subtests of which 0 failed
> 128 test cases of which 0 failed
> 0 test cases were skipped
> TEE test application done!
> root@imx6ullevk-sec:~#
> ```
> 
> @MrCry0 working fine here.

Yeah, I said - that is not an op-tee issue, but building one. Somehow factory built an older version of optee-test.

**Pull request merged**
