### PR TITLE
Feat/ostree for compose apps

### PR DESCRIPTION
**Pull request by mike-sul**
Adjust the compose preloading to "ostree for apps". Depends on https://github.com/foundriesio/ci-scripts/pull/110.

### CODE REVIEW

**Comment by doanac** [comment]
I guess this is really a single commit and depends on https://github.com/foundriesio/meta-lmp/pull/257/ correct?

**Comment by mike-sul** [comment]
> I guess this is really a single commit and depends on #257 correct?

correct

**Comment by ricardosalveti** [comment]
Please rebase.

**Comment by mike-sul** [comment]
@ricardosalveti, since this PR https://github.com/foundriesio/ci-scripts/pull/110 was merged, then the given PR is good to go. Tested it here https://github.com/foundriesio/ci-scripts/pull/110.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
