### PR TITLE
images/feature-debug: add more debug tools

### PR DESCRIPTION
**Pull request by mike-scott**
To help with HW bringup and debugging let's add the following
tools to the debug feature:
- screen
- tmux
- minicom
- devmem2

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
My thoughts here were to have a serial tool that the user is familiar with (we offer several), add a package manager to enable on-the-fly loading of packages, and devmem2 to allow for reading registers etc.

**Comment by doanac** [comment]
handy - but have we considered making a "dev" container instead? Just to help push people in the "containers can do it all" direction?

**Comment by mike-scott** [comment]
@doanac you would have to have that container pre-installed as in some cases you're debugging why the network isn't working, etc.

**Comment by doanac** [comment]
good point.

**Comment by mike-scott** [comment]
@rsalveti removed opkg

**Pull request merged**
