### PR TITLE
bsp: initramfs-ostree-lmp-recovery: adds stm32mp15-discov fw_env.config

### PR DESCRIPTION
**Pull request by quaresmajose**
commit [1] introduces fw_env.config for machine stm32mp15-eval but
commit [2] uses stm32mp1common machine override to fetch the fw_env.config
so fw_env.config of the stm32mp15-disco is needed too.

The machine stm32mp15-disco is currently broken:

```
ERROR: /lmp/build-stm32mp15-disco/conf/../../layers/meta-lmp/meta-lmp-base/recipes-core/images/initramfs-ostree-lmp-recovery.bb: Unable to get checksum for initramfs-ostree-lmp-recovery SRC_URI entry fw_env.config: file could not be found
```
[1] - a8616507 bsp: initramfs-ostree-lmp-recovery: add stm32mp15-eval
[2] - 0d95fdaf bsp: initramfs-ostree-lmp-recovery: add image config for stm32mp1common

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]

**Comment by ricardosalveti** [comment]
I'm not completely sure the device index is the same on both boards, will let @igoropaniuk to review this one.

**Review by igoropaniuk — CHANGES_REQUESTED** [review]
We can't use the same fw_config for evalation and disco boards, as both mmc id and offset of ubootenv are different:

https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/stm32mp15-disco/fw_env.config
https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/stm32mp15-eval/fw_env.config

**Comment by quaresmajose** [comment]
When I face this issue the stm32mp15-disco fw_config file not found when I am building but as you pointed it is on https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/stm32mp15-disco/fw_env.config so I will take another look.

**Comment by quaresmajose** [comment]
added the missing stm32mp15-discov fw_env.config and the build look good now

**Review by igoropaniuk — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
Nit on the commit message:

From: "bsp: initramfs-ostree-lmp-recovery: adds stm32mp15-discov fw_env.config"

To: "bsp: initramfs-ostree-lmp-recovery: add stm32mp15-disco fw_env.config"

Otherwise LGTM

**Comment by quaresmajose** [comment]
Fixed

**Pull request merged**
