### PR TITLE
[RFC] Imx8mq wks fixes

### PR DESCRIPTION
**Pull request by igoropaniuk**

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]
LGTM

**Comment by igoropaniuk** [comment]
Closing this PR, as this was addressed with a different solution (concatenating padding to SIT image)

**Pull request closed without merging**
