### PR TITLE
base: aktualizr-lite: bump to fe447e0

### PR DESCRIPTION
**Pull request by mike-sul**
Relevant changes:
- fe447e0 fixup! get currently installed apps correctly

Signed-off-by: Mike Sul <mike.sul@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Looks good. This makes me think we should probably have some test-plan type thing associated with this type of merge that @mwasilew can help do verification with.

**Comment by mwasilew** [comment]
If there is LmP build on creation of PR, this can be automatically tested before it's merged. At this point I can only see PRs to manifest built automatically. As for test plan part, there already is an entry in the doc, but no tests running yet.

**Comment by ricardosalveti** [comment]
> If there is LmP build on creation of PR, this can be automatically tested before it's merged. At this point I can only see PRs to manifest built automatically. As for test plan part, there already is an entry in the doc, but no tests running yet.

That would be ideal, but for us being able to test once we merge lmp-manifest is already a big plus at this stage.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
