### PR TITLE
allign with master meta-virt + meta-lts-mixins

### PR DESCRIPTION
**Pull request by quaresmajose**
With the bring-up of meta-lts-mixins and go-1.20 these will align with what is available in meta-virt master branch, dropping our forks:
```
- containerd-opencontainers
- docker-compose
- docker-ce
- runc-opencontainers
- skopeo
```

all the patch are backported from our `main-next`.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Which rev from meta-virt are you using here? Will check if there is something missing there.

**Comment by quaresmajose** [comment]
Tested on https://github.com/foundriesio/lmp-manifest/pull/305

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
I'm a bit afraid of the consequence of bringing several other non related changes to lmp (due master), so I'm inclined to first update the current stack in lmp itself (taking your patches and changes), and later moving to master, so we can better isolate the changes and issues.

Will propose just the container stack updates in a separated pr to start.

**Comment by quaresmajose** [comment]
> I'm a bit afraid of the consequence of bringing several other non related changes to lmp (due master), so I'm inclined to first update the current stack in lmp itself (taking your patches and changes), and later moving to master, so we can better isolate the changes and issues.
> 
> Will propose just the container stack updates in a separated pr to start.

I agree, switch to master is a big change on the stack.

**Pull request closed without merging**
