### PR TITLE
wireguard: remove upstreamed wg-quick append

### PR DESCRIPTION
**Pull request by jeromebrunet**
Foundries changes on wg-quick landed in meta-openembedded with commit f36a158aa0b6 ("wireguard-tools: Add a new package for wg-quick"). The bbappend in meta-lmp conflicts with this change.

ERROR: wireguard-tools-1.0.20210914-r0 do_package: QA Issue: wireguard-tools-wg-quick is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]

Removing the bbappend fixes the problem

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Thanks for the change, but this one is covered in https://github.com/foundriesio/meta-lmp/pull/788 already (which I should be merging later today).

**Comment by quaresmajose** [comment]
Hi @jeromebrunet we have the PR https://github.com/foundriesio/meta-lmp/pull/788 already to address this issue. We will merge it on next bump

**Comment by jeromebrunet** [comment]
Great. Your PR #788 targets. Can you apply it to `kirkstone` too ?

**Comment by ricardosalveti** [comment]
Available now in both main and kirkstone.

**Pull request closed without merging**
