### PR TITLE
Enable u-boot 2022.04 and kernel 5.15 for imx8mm

### PR DESCRIPTION
**Pull request by MrCry0**
Tested:
Flash/Load

lmp-base: imx8mm-lpddr4-evk: OK
lmp-mfgtool: imx8mm-lpddr4-evk: OK
lmp-mfgtool: imx8mm-lpddr4-evk-sec: OK
lmp: imx8mm-lpddr4-evk: OK
lmp: imx8mm-lpddr4-evk-sec: OK (open board with fused keys)
lmp: imx8mm-lpddr4-evk-ebbr: FAIL (u-boot-imx8mm-lpddr4-evk-ebbr.itb is too large)
Boot:
lmp-base: imx8mm-lpddr4-evk: OK
lmp-mfgtool: imx8mm-lpddr4-evk: OK
lmp-mfgtool: imx8mm-lpddr4-evk-sec: OK
lmp: imx8mm-lpddr4-evk: OK
lmp: imx8mm-lpddr4-evk-sec: OK (open board with fused keys)
Register
lmp: imx8mm-lpddr4-evk: OK
lmp: imx8mm-lpddr4-evk-sec: OK (open board with fused keys)
Update
lmp: imx8mm-lpddr4-evk: OK
lmp: imx8mm-lpddr4-evk-sec: OK (open board with fused keys)

### CODE REVIEW

**Comment by ricardosalveti** [comment]
0001-FIO-internal-arch-arm64-dts-imx8mp-enable-I2C5-bus.patch should be used when se05x is enabled, no?

https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_git.bb#L24

**Comment by ricardosalveti** [comment]
Will do a better review round tomorrow, but this should be aligned after https://github.com/foundriesio/lmp-manifest/pull/224.

**Comment by MrCry0** [comment]
> 0001-FIO-internal-arch-arm64-dts-imx8mp-enable-I2C5-bus.patch should be used when se05x is enabled, no?
> 
> https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_git.bb#L24

Good catch, thanks. I'll fix the commit https://github.com/foundriesio/meta-lmp/pull/856/commits/d41023c7fc39eecaca1c4a7a444701e9023b31f0

**Comment by ricardosalveti** [comment]
My only problem with this PR is that we are going to be updating the kernel for every imx target we support, and we're not yet aligned with the respective u-boot version (since this only enables for imx8mm), and this will for sure cause bugs and issues.

Can we have a separated recipe (different version, not git), with default preference -1 and force the update only for imx8mm? That way we can transition devices as we test and validate everything.

**Comment by ricardosalveti** [comment]
I'm getting the following trace when booting on my imx8mm evka:

```
[    2.636394] ------------[ cut here ]------------
[    2.641035] WARNING: CPU: 1 PID: 90 at drivers/reset/core.c:765 __reset_control_get_internal+0x150/0x170
[    2.650539] Modules linked in:
[    2.653601] CPU: 1 PID: 90 Comm: kworker/u8:2 Not tainted 5.15.60-lmp-standard #1
[    2.661096] Hardware name: FSL i.MX8MM LPDDR4 EVK with QCA WIFI revC board  (DT)
[    2.668502] Workqueue: events_unbound deferred_probe_work_func
[    2.674351] pstate: 20000005 (nzCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[    2.681323] pc : __reset_control_get_internal+0x150/0x170
[    2.686728] lr : __of_reset_control_get+0x178/0x1d4
[    2.691614] sp : ffffffc009f33980
[    2.694934] x29: ffffffc009f33980 x28: ffffff8055c08bf0 x27: ffffff8005ade538
[    2.702085] x26: 0000000000000001 x25: 0000000000000000 x24: 0000000000000001
[    2.709237] x23: 0000000000000000 x22: ffffff8003650980 x21: 0000000000000005
[    2.716389] x20: ffffff80036509a0 x19: ffffff8005b19a80 x18: ffffffffffffffff
[    2.723540] x17: 000000040044ffff x16: 00400032b5593519 x15: 0100000000000041
[    2.730692] x14: ffffffffffffffff x13: 0000000000000038 x12: 0101010101010101
[    2.737844] x11: 0000000000000000 x10: 0101010101010101 x9 : ffffffc00873bff8
[    2.744996] x8 : 7f7f7f7f7f7f7f7f x7 : 64622c6c766f21ff x6 : 802370771f481000
[    2.752148] x5 : fffffffdfdc09d94 x4 : 0000000000000000 x3 : 0000000000000001
[    2.759300] x2 : 0000000000000005 x1 : 0000000000000005 x0 : 0000000000000000
[    2.766454] Call trace:
[    2.768904]  __reset_control_get_internal+0x150/0x170
[    2.773966]  __of_reset_control_get+0x178/0x1d4
[    2.778502]  of_reset_control_array_get+0xb8/0x230
[    2.783302]  imx_sec_dsim_probe+0x23c/0x360
[    2.787494]  platform_probe+0x74/0xf0
[    2.791169]  really_probe+0xd4/0x474
[    2.794751]  __driver_probe_device+0x98/0x18c
[    2.799117]  driver_probe_device+0x48/0xe0
[    2.803222]  __device_attach_driver+0xb8/0x144
[    2.807676]  bus_for_each_drv+0x84/0xe0
[    2.811519]  __device_attach+0xb0/0x1f4
[    2.815363]  device_initial_probe+0x20/0x30
[    2.819557]  bus_probe_device+0xa8/0xb0
[    2.823402]  deferred_probe_work_func+0xa8/0xfc
[    2.827942]  process_one_work+0x220/0x4bc
[    2.831964]  worker_thread+0x2e8/0x464
[    2.835721]  kthread+0x148/0x160
[    2.838955]  ret_from_fork+0x10/0x20
[    2.842539] ---[ end trace 73392e3060407467 ]---
[    2.847511] ------------[ cut here ]------------
[    2.852142] WARNING: CPU: 1 PID: 90 at drivers/reset/core.c:765 __reset_control_get_internal+0x150/0x170
[    2.861638] Modules linked in:
[    2.864701] CPU: 1 PID: 90 Comm: kworker/u8:2 Tainted: G        W         5.15.60-lmp-standard #1
[    2.873582] Hardware name: FSL i.MX8MM LPDDR4 EVK with QCA WIFI revC board  (DT)
[    2.880990] Workqueue: events_unbound deferred_probe_work_func
[    2.886834] pstate: 20000005 (nzCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[    2.893804] pc : __reset_control_get_internal+0x150/0x170
[    2.899211] lr : __of_reset_control_get+0x178/0x1d4
[    2.904099] sp : ffffffc009f33980
[    2.907418] x29: ffffffc009f33980 x28: ffffff8055c08e00 x27: ffffff8005ade538
[    2.914569] x26: 0000000000000001 x25: 0000000000000000 x24: 0000000000000001
[    2.921721] x23: 0000000000000000 x22: ffffff8003650d80 x21: 0000000000000009
[    2.928873] x20: ffffff8003650da0 x19: ffffff8005b19d00 x18: ffffffffffffffff
[    2.936023] x17: 000000040044ffff x16: 00400032b5593519 x15: 0100000000000041
[    2.943175] x14: ffffffffffffffff x13: 0000000000000038 x12: 0101010101010101
[    2.950327] x11: 0000000000000000 x10: 0101010101010101 x9 : ffffffc00873bff8
[    2.957480] x8 : 7f7f7f7f7f7f7f7f x7 : 64622c6c766f21ff x6 : 802370771f481000
[    2.964633] x5 : fffffffdfdc09ddc x4 : 0000000000000000 x3 : 0000000000000001
[    2.971782] x2 : 0000000000000009 x1 : 0000000000000009 x0 : 0000000000000000
[    2.978934] Call trace:
[    2.981382]  __reset_control_get_internal+0x150/0x170
[    2.986440]  __of_reset_control_get+0x178/0x1d4
[    2.990978]  of_reset_control_array_get+0xb8/0x230
[    2.995777]  imx_sec_dsim_probe+0x23c/0x360
[    2.999969]  platform_probe+0x74/0xf0
[    3.003642]  really_probe+0xd4/0x474
[    3.007226]  __driver_probe_device+0x98/0x18c
[    3.011592]  driver_probe_device+0x48/0xe0
[    3.015697]  __device_attach_driver+0xb8/0x144
[    3.020152]  bus_for_each_drv+0x84/0xe0
[    3.023996]  __device_attach+0xb0/0x1f4
[    3.027840]  device_initial_probe+0x20/0x30
[    3.032034]  bus_probe_device+0xa8/0xb0
[    3.035879]  deferred_probe_work_func+0xa8/0xfc
[    3.040418]  process_one_work+0x220/0x4bc
[    3.044438]  worker_thread+0x2e8/0x464
[    3.048193]  kthread+0x148/0x160
[    3.051426]  ret_from_fork+0x10/0x20
[    3.055012] ---[ end trace 73392e3060407468 ]---
[    3.059772] ------------[ cut here ]------------
[    3.064399] WARNING: CPU: 1 PID: 90 at drivers/reset/core.c:765 __reset_control_get_internal+0x150/0x170
[    3.073894] Modules linked in:
[    3.076955] CPU: 1 PID: 90 Comm: kworker/u8:2 Tainted: G        W         5.15.60-lmp-standard #1
[    3.085836] Hardware name: FSL i.MX8MM LPDDR4 EVK with QCA WIFI revC board  (DT)
[    3.093242] Workqueue: events_unbound deferred_probe_work_func
[    3.099087] pstate: 20000005 (nzCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[    3.106057] pc : __reset_control_get_internal+0x150/0x170
[    3.111462] lr : __of_reset_control_get+0x178/0x1d4
[    3.116345] sp : ffffffc009f33980
[    3.119666] x29: ffffffc009f33980 x28: ffffff8055c09010 x27: ffffff8053630fb8
[    3.126817] x26: 0000000000000001 x25: 0000000000000000 x24: 0000000000000001
[    3.133968] x23: 0000000000000000 x22: ffffff8003651c80 x21: 0000000000000001
[    3.141121] x20: ffffff8003651ca0 x19: ffffff8005b19200 x18: ffffffffffffffff
[    3.148270] x17: 000000040044ffff x16: 00400032b5593519 x15: ffffffc008851a20
[    3.155422] x14: ffffffc008851310 x13: ffffffc00884e114 x12: ffffffc008851798
[    3.162574] x11: 0000000000000000 x10: 0101010101010101 x9 : ffffffc00873bff8
[    3.169726] x8 : 7f7f7f7f7f7f7f7f x7 : 64622c6c766f21ff x6 : 802370771f481000
[    3.176878] x5 : fffffffdfdc09e2c x4 : 0000000000000000 x3 : 0000000000000001
[    3.184029] x2 : 0000000000000001 x1 : 0000000000000001 x0 : 0000000000000000
[    3.191180] Call trace:
[    3.193630]  __reset_control_get_internal+0x150/0x170
[    3.198689]  __of_reset_control_get+0x178/0x1d4
[    3.203227]  of_reset_control_array_get+0xb8/0x230
[    3.208025]  imx_sec_dsim_probe+0x23c/0x360
[    3.212215]  platform_probe+0x74/0xf0
[    3.215885]  really_probe+0xd4/0x474
[    3.219471]  __driver_probe_device+0x98/0x18c
[    3.223836]  driver_probe_device+0x48/0xe0
[    3.227941]  __device_attach_driver+0xb8/0x144
[    3.232396]  bus_for_each_drv+0x84/0xe0
[    3.236237]  __device_attach+0xb0/0x1f4
[    3.240081]  device_initial_probe+0x20/0x30
[    3.244275]  bus_probe_device+0xa8/0xb0
[    3.248119]  deferred_probe_work_func+0xa8/0xfc
[    3.252658]  process_one_work+0x220/0x4bc
[    3.256676]  worker_thread+0x2e8/0x464
[    3.260432]  kthread+0x148/0x160
[    3.263667]  ret_from_fork+0x10/0x20
[    3.267253] ---[ end trace 73392e3060407469 ]---
[    3.272253] imx_sec_dsim_drv 32e10000.mipi_dsi: no invalid reset control exists
[    3.279659] imx_sec_dsim_drv: probe of 32e10000.mipi_dsi failed with error -22
...
[    5.851388] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[   30.546340] pci 0000:00:00.0: imx6_pcie_l1ss_quirk+0x0/0x1c0 took 24110965 usecs
```

It boots in the end, besides the trace and a large delay at imx6_pcie_l1ss_quirk.

**Comment by MrCry0** [comment]
> My only problem with this PR is that we are going to be updating the kernel for every imx target we support, and we're not yet aligned with the respective u-boot version (since this only enables for imx8mm), and this will for sure cause bugs and issues.
> 
> Can we have a separated recipe (different version, not git), with default preference -1 and force the update only for imx8mm? That way we can transition devices as we test and validate everything.

Makes sense. Will do it today.

**Comment by MrCry0** [comment]
> My only problem with this PR is that we are going to be updating the kernel for every imx target we support, and we're not yet aligned with the respective u-boot version (since this only enables for imx8mm), and this will for sure cause bugs and issues.
> 
> Can we have a separated recipe (different version, not git), with default preference -1 and force the update only for imx8mm? That way we can transition devices as we test and validate everything.

@ricardosalveti Done

**Comment by MrCry0** [comment]
> I'm getting the following trace when booting on my imx8mm evka:
> 
> ```
> [    2.636394] ------------[ cut here ]------------
> [    2.641035] WARNING: CPU: 1 PID: 90 at drivers/reset/core.c:765 __reset_control_get_internal+0x150/0x170
> [    2.650539] Modules linked in:
> [    2.653601] CPU: 1 PID: 90 Comm: kworker/u8:2 Not tainted 5.15.60-lmp-standard #1
> [    2.661096] Hardware name: FSL i.MX8MM LPDDR4 EVK with QCA WIFI revC board  (DT)
> [    2.668502] Workqueue: events_unbound deferred_probe_work_func
> [    2.674351] pstate: 20000005 (nzCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
> [    2.681323] pc : __reset_control_get_internal+0x150/0x170
> [    2.686728] lr : __of_reset_control_get+0x178/0x1d4
> [    2.691614] sp : ffffffc009f33980
> [    2.694934] x29: ffffffc009f33980 x28: ffffff8055c08bf0 x27: ffffff8005ade538
> [    2.702085] x26: 0000000000000001 x25: 0000000000000000 x24: 0000000000000001
> [    2.709237] x23: 0000000000000000 x22: ffffff8003650980 x21: 0000000000000005
> [    2.716389] x20: ffffff80036509a0 x19: ffffff8005b19a80 x18: ffffffffffffffff
> [    2.723540] x17: 000000040044ffff x16: 00400032b5593519 x15: 0100000000000041
> [    2.730692] x14: ffffffffffffffff x13: 0000000000000038 x12: 0101010101010101
> [    2.737844] x11: 0000000000000000 x10: 0101010101010101 x9 : ffffffc00873bff8
> [    2.744996] x8 : 7f7f7f7f7f7f7f7f x7 : 64622c6c766f21ff x6 : 802370771f481000
> [    2.752148] x5 : fffffffdfdc09d94 x4 : 0000000000000000 x3 : 0000000000000001
> [    2.759300] x2 : 0000000000000005 x1 : 0000000000000005 x0 : 0000000000000000
> [    2.766454] Call trace:
> [    2.768904]  __reset_control_get_internal+0x150/0x170
> [    2.773966]  __of_reset_control_get+0x178/0x1d4
> [    2.778502]  of_reset_control_array_get+0xb8/0x230
> [    2.783302]  imx_sec_dsim_probe+0x23c/0x360
...
> [    3.267253] ---[ end trace 73392e3060407469 ]---
> [    3.272253] imx_sec_dsim_drv 32e10000.mipi_dsi: no invalid reset control exists
> [    3.279659] imx_sec_dsim_drv: probe of 32e10000.mipi_dsi failed with error -22

The warnings are from the MIPI DSI driver. If we need this, I'll investigate the issue, otherwise, we could just disable this driver.

> ...
> [    5.851388] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
> [   30.546340] pci 0000:00:00.0: imx6_pcie_l1ss_quirk+0x0/0x1c0 took 24110965 usecs
> ```
> 
> It boots in the end, besides the trace and a large delay at imx6_pcie_l1ss_quirk.

Yeah, there is a delay on PCIe probing, I had the same with the original NXP 5.15*-2.0.0. Retesting on 2.1.0.

**Comment by MrCry0** [comment]
> It boots in the end, besides the trace and a large delay at imx6_pcie_l1ss_quirk.

This issue is not reproduced on 5.15.60-imx-2.1.0 with the latest changes. Updating the PR.

**Review by quaresmajose — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
Nice, thanks for the fixes, building today and will run some proper testing tomorrow!

**Review by ricardosalveti — APPROVED** [review]
LGTM, great work, working nicely now.

Still a few more things to validate, but let's merge and improve.

**Pull request merged**
