### PR TITLE
Moving mx6u* to the 5.15.52-2.1.0 NXP BSP

### PR DESCRIPTION
**Pull request by MrCry0**
CI test: https://github.com/foundriesio/lmp-manifest/pull/260

Validation:

- [x] mx6ul
   - [x] build tested
   - [x] normal test run
   - [x] base test run
   - [x] mfgtools
- [x] mx6ull
   - [x] build tested
   - [x] normal test run
   - [x] base test run
   - [x] sec test run 
   - [x] mfgtools

### CODE REVIEW

**Comment by ricardosalveti** [comment]
With https://github.com/foundriesio/lmp-kernel-cache/pull/75 I can get to a prompt, but the boot itself is quite slow (tested with the BSP tag and BSP-only config and it didn't even boot for me).

Looks like something is wrong at the cpu clock/idle side, or even emmc/sdcard performance, but since this is the same on the BSP only (and we don't have any customer requiring this one on kirkstone yet), I'm ok to merge.

**Comment by ricardosalveti** [comment]
@MrCry0 can you do the kmeta bump and consolidate the changes from https://github.com/foundriesio/meta-lmp/pull/937 here (if not done already)? Planning on merging this tomorrow.

**Comment by MrCry0** [comment]
> @MrCry0 can you do the kmeta bump and consolidate the changes from #937 here (if not done already)? Planning on merging this tomorrow.

@ricardosalveti Sure, I'm doing this right now.

**Comment by ricardosalveti** [comment]
6ul base needs:

```
rsalveti@evatuf:~/build/lmp/layers/meta-lmp$ git diff
diff --git a/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ulevk/lmp-base.cfg b/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ulevk/lmp-base.cfg
index 919fe631..65bb544f 100644
--- a/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ulevk/lmp-base.cfg
+++ b/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ulevk/lmp-base.cfg
@@ -73,7 +73,6 @@ CONFIG_CMD_HASH=y
 # CONFIG_FSL_CAAM is not set
 CONFIG_MISC=y
 # CONFIG_CHIMP_OPTEE is not set
-# CONFIG_CMD_BOOTZ is not set
 # CONFIG_DM_VIDEO is not set
 # CONFIG_FSL_DCP_RNG is not set
 # CONFIG_OPTEE_TA_AVB is not set
```

**Comment by ricardosalveti** [comment]
Also missing updating linux-lmp-dev-mfgtool (to 5.15).

While it boots, it is still super slow, need a bit more debugging.

**Comment by MrCry0** [comment]
> Also missing updating linux-lmp-dev-mfgtool (to 5.15).
> 

Got power back! Working on it.

> While it boots, it is still super slow, need a bit more debugging.

Yeap, noted that. I'll debug this tomorrow.

**Comment by ricardosalveti** [comment]
@MrCry0 https://github.com/foundriesio/lmp-kernel-cache/pull/76 should fix the slow boot.

**Comment by MrCry0** [comment]
> @MrCry0 [foundriesio/lmp-kernel-cache#76](https://github.com/foundriesio/lmp-kernel-cache/pull/76) should fix the slow boot.

Updated.

**Comment by ricardosalveti** [comment]
Thanks a lot, I think we're good to merge and start doing a wider testing on this.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
