### PR TITLE
Nerdctl: fix install path

### PR DESCRIPTION
**Pull request by quaresmajose**

### CODE REVIEW

**Comment by mike-sul** [comment]
I am testing it my factory...

**Comment by ricardosalveti** [comment]
Please change the patch subject to prepend "base: ".

**Comment by ricardosalveti** [comment]
Just noticed the path is also incorrect, need to be under meta-lmp-base otherwise it will be ignored.

**Comment by quaresmajose** [comment]
I am trying to build it locally but it fetch this world and the other

**Comment by quaresmajose** [comment]
```
ERROR: nerdctl-v0.18.0-r0 do_package: QA Issue: nerdctl: Files/directories were installed but not shipped in any package:
  /bin
  /bin/nerdctl
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
nerdctl: 2 installed and not shipped files. [installed-vs-shipped]
ERROR: nerdctl-v0.18.0-r0 do_package: Fatal QA errors were found, failing task.
```
Tested locally and the issue is fixed

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
