### PR TITLE
TI stable kirkstone bump

### PR DESCRIPTION
**Pull request by quaresmajose**
Wainting the last piece to be merged https://lists.yoctoproject.org/g/meta-ti/topic/102547765

### CODE REVIEW

**Comment by quaresmajose** [comment]
last piece to unblock the fixed, we can bump to the latest meta-ti kirkstone
```patch
--- a/meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
+++ b/meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
@@ -641,6 +641,7 @@ WKS_FILES:sota:versal = "sdimage-sota.wks"
 
 # TI Generic (BSP)
 TI_COMMON_DEPLOY = "${DEPLOY_DIR}"
+DEPLOY_DIR_SPDX:append = "${@'/${MACHINE}' if 'ti-soc' in d.getVar('SOC_FAMILY').split(':') else ''}"
 UBOOT_SIGN_ENABLE:sota:k3 = "1"
 UBOOT_SIGN_KEYDIR:k3 ?= "${TOPDIR}/conf/keys"
 FIT_HASH_ALG:sota:k3 ?= "sha256"
```

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by quaresmajose** [comment]
validated with https://git.yoctoproject.org/meta-ti/commit/?h=kirkstone&id=5769fcfb036661a3ceaeb8f90d8a9928e3d29199

**Review by ricardosalveti — APPROVED** [review]
LGTM, will also bump lmp-manifest, just working on finding a kernel rev that works as the latest is failing to work on am62.

**Pull request merged**
