### PR TITLE
bsp: support: mfgtool-files: imx8qm-mek: replace "reboot" command

### PR DESCRIPTION
**Pull request by vanmaegima**
"reboot" command is not available for apalis-imx8 u-boot,
so replace it with "reset".

### CODE REVIEW

**Comment by vanmaegima** [comment]
We ran into this error in apalis-imx8, however I do see:
$ git grep reboot | grep imx8qm
meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8qm-mek/boot.cmd:setenv do_reboot "reboot"
I wonder if this works for mek.

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
