### PR TITLE
OP-TEE 3.15 and SE05X support via the public plug-and-trust

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
@ldts still to test on imx6/armhf, only validated on imx8mm evk at this point.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by igoropaniuk — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Pull request merged**
