### PR TITLE
bsp: uz: u-boot-xlnx: drop bootcount support

### PR DESCRIPTION
**Pull request by igoropaniuk**
Drop bootcount support in U-Boot, as we implement the same functionality
in boot.cmd.

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

### CODE REVIEW

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by mike-scott — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGMT

**Pull request merged**
