### PR TITLE
[WIP] Moving mx6ull to the 5.15.52-2.1.0 NXP BSP

### PR DESCRIPTION
**Pull request by MrCry0**
The hack is removed. The only major issue is with getting the prompt.
 ̶T̶h̶e̶r̶e̶ ̶i̶s̶ ̶a̶ ̶t̶e̶m̶p̶o̶r̶a̶r̶y̶ ̶h̶a̶c̶k̶ ̶f̶o̶r̶ ̶n̶o̶t̶ ̶a̶p̶p̶l̶y̶i̶n̶g̶ ̶o̶v̶e̶r̶l̶a̶y̶ ̶p̶r̶e̶p̶a̶r̶e̶d̶ ̶b̶y̶ ̶O̶P̶-̶T̶E̶E̶ ̶o̶n̶ ̶t̶h̶e̶ ̶k̶e̶r̶n̶e̶l̶ ̶D̶T̶,̶ ̶w̶h̶i̶c̶h̶ ̶u̶n̶l̶o̶c̶k̶s̶ ̶b̶o̶o̶t̶i̶n̶g̶ ̶`̶l̶m̶p̶-̶f̶a̶c̶t̶o̶r̶y̶-̶i̶m̶a̶g̶e̶`̶.̶

### CODE REVIEW

**Comment by ricardosalveti** [comment]
I was able to get it to boot to the kernel with the overlay after applying the following diff:

```
diff --git a/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ullevk/lmp.cfg b/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ullevk/lmp.cfg
index 54733555..80e64e28 100644
--- a/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ullevk/lmp.cfg
+++ b/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ullevk/lmp.cfg
@@ -71,11 +71,14 @@ CONFIG_USE_BOOTCOMMAND=y
 CONFIG_BOOTCOMMAND="setenv script_addr 0x85000000; setenv verify 1; source ${script_addr}; reset"
 CONFIG_DEFAULT_FDT_FILE="imx6ull-14x14-evk"
 CONFIG_SPL_LOAD_FIT_ADDRESS=0x80800000
-CONFIG_CMD_BOOTZ=y
 CONFIG_SYS_I2C_MXC=y
 CONFIG_SYS_I2C_MXC_I2C1=y
 CONFIG_SYS_I2C_MXC_I2C2=y
 CONFIG_RSA=y
+# CONFIG_DM_VIDEO is not set
+# CONFIG_OPTEE_TA_AVB is not set
+# CONFIG_CHIMP_OPTEE is not set
+# CONFIG_CMD_BOOTZ is not set
 # CONFIG_ANDROID_BOOT_IMAGE is not set
 # CONFIG_NET is not set
 # CONFIG_USB is not set
```

I noticed they enabled video on this, and my bet is that it might be corrupting the area used for the overlay (since the address is not really protected by u-boot).

Now getting some weird issues during boot, unable to get to the prompt (some systemd services failing, investigating).

**Comment by ricardosalveti** [comment]
Same kernel rev, but with the BSP defconfig (imx_v7_defconfig) boots fine, so it is either something we're enabling that is not properly supported or we might be missing something, will debug more tomorrow.

**Comment by MrCry0** [comment]
> I was able to get it to boot to the kernel with the overlay after applying the following diff:

Thanks, it works, updated the PR.

**Comment by MrCry0** [comment]
> Same kernel rev, but with the BSP defconfig (imx_v7_defconfig) boots fine, so it is either something we're enabling that is not properly supported or we might be missing something, will debug more tomorrow.

@ricardosalveti I'm testing the possible fix.

**Comment by ricardosalveti** [comment]
With https://github.com/foundriesio/lmp-kernel-cache/pull/74 I'm able to get it to boot.

**Comment by MrCry0** [comment]
> With [foundriesio/lmp-kernel-cache#74](https://github.com/foundriesio/lmp-kernel-cache/pull/74) I'm able to get it to boot.

@ricardosalveti Thanks! I'll add bumping to that version once it is merged. I just got power back again :(

**Comment by ricardosalveti** [comment]
> > With [foundriesio/lmp-kernel-cache#74](https://github.com/foundriesio/lmp-kernel-cache/pull/74) I'm able to get it to boot.
> 
> @ricardosalveti Thanks! I'll add bumping to that version once it is merged. I just got power back again :(

Done.

One thing I noticed is that we might need to apply the diff I suggested in lmp-base and mfgtools as well.

**Comment by MrCry0** [comment]
Superseded by PR #https://github.com/foundriesio/meta-lmp/pull/941

**Pull request closed without merging**
