### PR TITLE
bsp: imx8mm-lpddr4-evk: lmp-ebbr: disable options due size

### PR DESCRIPTION
**Pull request by ricardosalveti**
Disable options not strictly required by EBBR in order to get it down to the maximum size for the primary bootloader image.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

### CODE REVIEW

**Comment by MrCry0** [comment]
> @MrCry0 build tested (and tested the flashing part), but since my board is closed, I'm unable to boot test the image.
> 
> If you can give it a try with your board (in case yours is still open), we should know if we can boot or not with these changes (I think it should be fine as they are similar to what I did for imx8mq, which I tested locally).

@ricardosalveti sure, testing. Thanks for the fix, I was not aware of non-essential features for that target.

**Comment by MrCry0** [comment]
> @MrCry0 build tested (and tested the flashing part), but since my board is closed, I'm unable to boot test the image.
> 
> If you can give it a try with your board (in case yours is still open), we should know if we can boot or not with these changes (I think it should be fine as they are similar to what I did for imx8mq, which I tested locally).

Seems to boot properly.

```
U-Boot SPL 2022.04+fio+g92012fed80 (Nov 10 2022 - 16:25:08 +0000)
...
NOTICE:  BL31: v2.6(release):android-12.1.0_1.0.0-0-gc688807dd-dirty
...
I/TC: OP-TEE version: 3.18.0-122-gf2159b5a0+fio (gcc version 11.3.0 (GCC)) #1 Thu Nov 10 16:29:05 UTC 2022 aarch64
...
U-Boot 2022.04+fio+g92012fed80 (Nov 10 2022 - 16:25:08 +0000)
  Booting `Linux-microPlatform 4.0.5 (ostree:0)'

EFI stub: Booting Linux Kernel...
EFI stub: EFI_RNG_PROTOCOL unavailable
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services...
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.15.77-lmp-standard (oe-user@oe-host) (aarch64-lmp-linux-gcc (GCC) 11.3.0, GNU ld (GNU Binutils) 2.38.20220708) #1 SMP PREEMPT Mon Nov 14 14:09:49 UTC 2022
[    0.000000] Machine model: FSL i.MX8MM LPDDR4 EVK with QCA WIFI revC board 
[    0.000000] earlycon: ec_imx6q0 at MMIO 0x0000000030890000 (options '115200')
[    0.000000] printk: bootconsole [ec_imx6q0] enabled
[    0.000000] efi: EFI v2.90 by Das U-Boot
...
Linux-microPlatform 4.0.5 imx8mm-lpddr4-evk-ebbr -

imx8mm-lpddr4-evk-ebbr login:
Password:
fio@imx8mm-lpddr4-evk-ebbr:~$ uname -a
Linux imx8mm-lpddr4-evk-ebbr 5.15.77-lmp-standard #1 SMP PREEMPT Mon Nov 14 14:09:49 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
> @ricardosalveti sure, testing. Thanks for the fix, I was not aware of non-essential features for that target.

Not every option necessarily is required for the certification, but we can fight those later if we get to the point of having to re-certify this build. At this stage I'm more concerned that we can get a build that uses the u-boot -> uefi flow.

**Comment by ricardosalveti** [comment]
@MrCry0 thanks for testing it!

**Pull request merged**
