### PR TITLE
bsp: imx-mkimage: drop SPL-only signing patch

### PR DESCRIPTION
**Pull request by mike-scott**
This patch was a work around for our signing script which was catenating the CSF binary
to the SPL/imx-boot.  This has been corrected now to insert at the correct location.

SoCs such as i.MX8M Plus and Nano require the additional CSF padding space even when not signed.

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
NOTE: This requires: https://github.com/foundriesio/lmp-tools/pull/25

**Comment by MrCry0** [comment]
@mike-scott could you please add a reference to the commit with a fix to the commit message. It eases determining the correct pair of meta-lmp and lmp-tool versions.

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM, can be merged after addressing the comment from @MrCry0.

**Comment by ricardosalveti** [comment]
Will merge manually with the extra pointer to the lmp-tools change in order to run another lmp full build run.

**Comment by ricardosalveti** [comment]
https://github.com/foundriesio/meta-lmp/commit/fb48a80b1ac143e645c581d55cd1ea08c4b282e7

**Pull request closed without merging**
