### PR TITLE
Switch meta-virt to the scarthgap branch

### PR DESCRIPTION
**Pull request by quaresmajose**
Switch to https://git.yoctoproject.org/meta-virtualization/log/?h=scarthgap in preparation for the scarthgap release.

We will be still on kirkstone for the overall layers but to reduce the friction and to start do more testings with scarthgap material we will start with the meta-virtualization that works well with the golang present on the meta-lts-mixin layer and this layer is more isolated than the others in terms of dependencies

### CODE REVIEW

**Comment by ricardosalveti** [comment]
On the commits that are dropping the recipes, please explain why and how that matches with the ones from meta-virt.

**Comment by quaresmajose** [comment]
> Maybe you could add more information in the PR description regarding what is the overall plan, why are you going to scarthgap but have a commit adding kirkstone compatibility.
> 
> I mean, describe the overall plan, what is the main goal.

add a description on the PR

**Comment by quaresmajose** [comment]
> On the commits that are dropping the recipes, please explain why and how that matches with the ones from meta-virt.

I will add the missing information today

**Comment by quaresmajose** [comment]
> On the commits that are dropping the recipes, please explain why and how that matches with the ones from meta-virt.

done

**Review by MrCry0 — APPROVED** [review]

**Comment by quaresmajose** [comment]
This was tested and validated the scarthgap but I need to re-write the commits to align with the versions available on the current meta-virt scarthgap branch.

**Comment by quaresmajose** [comment]
main will jump directly to scarthgap

**Pull request closed without merging**
