### PR TITLE
Move fiovb to MACHINE_FEATURES and enabled for optee-os-fio-mfgtool

### PR DESCRIPTION
**Pull request by ricardosalveti**
Migrate fiovb from SOTA_EXTRA_CLIENT_FEATURES to MACHINE_FEATURES (as it is specific to the hw platform) and fix fiovb/early ta support for optee-os-fio-mfgtool.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
@mwasilew this should fix the lack of fiovb support in the mfgtools build.

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Comment by mwasilew** [comment]
Isn't imx8mp missing?

**Review by quaresmajose — APPROVED** [review]

**Comment by quaresmajose** [comment]
> Isn't imx8mp missing?

With this patch the SOTA_EXTRA_CLIENT_FEATURES is not used anymore

**Comment by mwasilew** [comment]
Yes, I understand that. It was replaced with MACHINE_FEATURES. However only imx8mm-lpddr4-evk-sec has fiovb added to it's MACHINE_FEATURES. We also support imx8mp-lpddr4-evk-sec and imx6ull-evk-sec. They don't seem to be present in this patch.

**Comment by quaresmajose** [comment]
yes, it isn't but from what I've checked it wasn't before either. anyway @ricardosalveti or another with more context can give a better answer than mine

**Comment by mwasilew** [comment]
IIUC it should be there. I only tested on a closed imx8mm but I think the same problem should come up on other NXP boards. Let's wait for @rsalveti to comment.

**Comment by ricardosalveti** [comment]
Yes, it was already missing for a few other targets, let me update to include the missing ones.

**Comment by ricardosalveti** [comment]
Added for 8mp as well.

**Pull request merged**
