### PR TITLE
[Backport Honister] bluez5: enable using libedit

### PR DESCRIPTION
**Pull request by MrCry0**
The backported version of enabling `bluetoothctl` with `libedit`.

@vanmaegima this version can be used in customers' factories.

### CODE REVIEW

**Comment by vanmaegima** [comment]
@MrCry0 thanks for this, I can test it on the customer factory next week, is this ok?

**Review by quaresmajose — APPROVED** [review]

**Comment by MrCry0** [comment]
> @MrCry0 thanks for this, I can test it on the customer factory next week, is this ok?

Sure, no problem! Just remember the `bluetooth.service` is needed to be started.

**Review by vanmaegima — APPROVED** [review]
Tested on a v86 factory and it works, thanks for this!

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
