### PR TITLE
nxp-bsp-update: switch imx8mm-*

### PR DESCRIPTION
**Pull request by MrCry0**
**Tested:**
**Flash/Load**
- lmp-base: imx8mm-lpddr4-evk: **OK**
- lmp-mfgtool: imx8mm-lpddr4-evk: **OK**
- lmp-mfgtool: imx8mm-lpddr4-evk-sec: **OK**
- lmp: imx8mm-lpddr4-evk: **OK**
- lmp: imx8mm-lpddr4-evk-sec: **OK** (open board with fused keys)
- lmp: imx8mm-lpddr4-evk-ebbr: **FAIL** (u-boot-imx8mm-lpddr4-evk-ebbr.itb is too large)
**Boot:**
- lmp-base: imx8mm-lpddr4-evk: **OK**
- lmp-mfgtool: imx8mm-lpddr4-evk: **OK**
- lmp-mfgtool: imx8mm-lpddr4-evk-sec: **OK**
- lmp: imx8mm-lpddr4-evk: **OK**
- lmp: imx8mm-lpddr4-evk-sec: **OK** (open board with fused keys)
**Register**
- lmp: imx8mm-lpddr4-evk: **OK**
- lmp: imx8mm-lpddr4-evk-sec: **OK** (open board with fused keys)
**Update**
- lmp: imx8mm-lpddr4-evk: **OK**
- lmp: imx8mm-lpddr4-evk-sec: **OK** (open board with fused keys)

**WARNING** This PR should be merged **ONLY** after merging the https://github.com/foundriesio/lmp-kernel-cache/pull/66 and replacing the latest commit by bumping one. The previous version of `lmp-kernel-cache` doesn't allow im8mm* to boot properly.

### CODE REVIEW

**Comment by quaresmajose** [comment]
Maybe rebase the `main-nxp-bsp-update` branch cleanup a bit the commit list in this PR as only the last 4 is merged not in `main`

**Comment by MrCry0** [comment]
> Maybe rebase the `main-nxp-bsp-update` branch cleanup a bit the commit list in this PR as only the last 4 is not merged in `main`

Makes sense. @ricardosalveti which merge strategy will be for the branch `main-nxp-bsp-update`? Will we merge it to the `main` or should we keep everything rebased to `main`?

**Review by angolini — APPROVED** [review]

**Comment by MrCry0** [comment]
> Maybe rebase the `main-nxp-bsp-update` branch cleanup a bit the commit list in this PR as only the last 4 is not merged in `main`

@quaresmajose done.

**Review by quaresmajose — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
LGTM

**Pull request merged**
