### PR TITLE
meta-ti stable update

### PR DESCRIPTION
**Pull request by quaresmajose**
Required to build latest kirktone, the kernel is bumped to the latest in the dunfell branch.

* bsp: linux-lmp-ti-staging: bump to 5.10.158
* Revert "bsp: u-boot-ti-staging: update to 08.04.00.005"
* Revert "bsp: lmp-machine-custom: ti-soc: update ti-linux-fw to 08.04.00.005"
* Revert "bsp: meta-ti-bsp: trusted-firmware-a: update to 08.04.00.005"

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]

**Comment by quaresmajose** [comment]
Will be tested in https://github.com/foundriesio/lmp-manifest/pull/233

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by quaresmajose** [comment]
Depends on https://github.com/foundriesio/meta-lmp/pull/1008 that should be merged first.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
