### PR TITLE
Set of kernel recipe stable updates

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Test PR available at https://github.com/foundriesio/lmp-manifest/pull/145

**Review by vanmaegima — APPROVED** [review]

**Comment by ricardosalveti** [comment]
Boot tested on intel, qemuarm, qemuarm64, qemurisc64, uz3eg-iocc, freedom-u540, stm32mp1-disco, beaglebone-yocto, imx8mmevk, imx8mqevk, apalis-imx6 and imx6ullevk.

**Comment by ricardosalveti** [comment]
@Tim-Anderson from my list it is just missing am64xx-sk.

**Comment by ricardosalveti** [comment]
Force push to update linux-lmp-rt to use v5.10.27-rt36 instead of v5.10.30-rt37, which fails to build.

**Review by angolini — APPROVED** [review]

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
That should do it. LGTM

**Pull request merged**
