### PR TITLE
bsp: kernel-modules: generalize imx-gpu-viv version

### PR DESCRIPTION
**Pull request by MrCry0**
bsp: kernel-modules: generalize imx-gpu-viv version
      
      As the bbappend recipe doesn't bind to a specific version of
      imx-gpu-viv, make it general.

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>

### CODE REVIEW

**Comment by quaresmajose** [comment]
Good catch! as the content of this append can by applied to any version is better to have the append agnostic to version
and rename it to `kernel-module-imx-gpu-viv_%.bbappend`

**Review by quaresmajose — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by MrCry0** [comment]
> Good catch! as the content of this append can by applied to any version is better to have the append agnostic to version and rename it to `kernel-module-imx-gpu-viv_%.bbappend`

Thanks, it's way better for this case :)

**Pull request merged**
