### PR TITLE
base: u-boot-fio: 2021.04: bump to 08349585ff

### PR DESCRIPTION
**Pull request by vanmaegima**
Relevant changes:
- 08349585ff [FIO internal] cmd: fiovb: increase fiovb_name buffer

Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

### CODE REVIEW

**Comment by vanmaegima** [comment]
@MrCry0 if possible, I'd like to include the above u-boot commit in v85

**Comment by MrCry0** [comment]
Sure, it's improtant.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by MrCry0** [comment]
@vanmaegima sorry for mis-closing :) I misread "Close with comment" as a "Close THIS comment". Again :)

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Pull request merged**
