### PR TITLE
nvidia: enable optee-os from source (instead of pre-built)

### PR DESCRIPTION
**Pull request by ricardosalveti**
This also allows us to be compatible with latest meta-tegra changes.

### CODE REVIEW

**Comment by quaresmajose** [comment]
Can you please build some machine from meta-ti with this change in place, in main-next I have a bunch of issues during bitbake parsing

**Review by MrCry0 — APPROVED** [review]
LGTM. Not tested.

**Comment by ricardosalveti** [comment]
> Can you please build some machine from meta-ti with this change in place, in main-next I have a bunch of issues during bitbake parsing

Can you dump the parsing issues you're having? Meanwhile I will try main-next locally.

**Comment by quaresmajose** [comment]
> > Can you please build some machine from meta-ti with this change in place, in main-next I have a bunch of issues during bitbake parsing
> 
> Can you dump the parsing issues you're having? Meanwhile I will try main-next locally.

I can be only happen on main-next, need to do another try

**Review by quaresmajose — APPROVED** [review]
LGTM

**Pull request merged**
