### PR TITLE
base: rs: aktualizr: bump version to 1345b23

### PR DESCRIPTION
**Pull request by detsch**
Relevant changes:
- a11bf7d cmake: Add BUILD_P11 option to aklite
- 0bcf0f1 offline: Require all enabled apps for offline update

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]

**Review by mike-sul — APPROVED** [review]

**Review by mike-sul — CHANGES_REQUESTED** [review]
There is a typo/mistake in the given aklite version. Let's fix it at first and then bump another aklite version into this PR.

**Comment by detsch** [comment]
Rebased and included aklite fixes and improvements related to commit `0bcf0f1`. No need to change the list of relevant changes IMO.

**Comment by mike-sul** [comment]
> Rebased and included aklite fixes and improvements related to commit `0bcf0f1`. No need to change the list of relevant changes IMO.

Yep, it's optional, the hash commit specified in the commit is not correct now, though.

**Review by mike-sul — APPROVED** [review]

**Comment by mike-sul** [comment]
This version works fine, I tested it quite well.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by quaresmajose** [comment]
just fyi, test this PR in lmp-base and the build issue is now fixed

**Comment by MrCry0** [comment]
> just fyi, test this PR in lmp-base and the build issue is now fixed

yeah, I confirm:  I reverted my temp revert  :) and built the new aktualizr successfully

**Pull request merged**
