### PR TITLE
Switch imx6ullevk and imx6ullevk-sec to u-boot 2021.04

### PR DESCRIPTION
**Pull request by MrCry0**
This PR enables building and successfully booting the imx6ullevk and imx6ullevk-sec targets with u-boot 2021.04+imx_5.10.35-2.0.0-fio and kernel lf-5.10.y.

**WARNING**: The [PR 110](https://github.com/foundriesio/u-boot/pull/110) should be merged before.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
This is the right branch for meta-lmp, pre-* is just for manifest (https://github.com/foundriesio/lmp-manifest/tree/pre-v84-ebbr-nxp).

**Review by angolini — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Comment by MrCry0** [comment]
I've just realized that GitHub changes original commit refs in a target branch on merging PR.
Great, so all bumping commits should be updated after merging child PRs.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
