### PR TITLE
Update TI BSP to 09.00.00.003

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Replaces https://github.com/foundriesio/meta-lmp/pull/1174

**Comment by ricardosalveti** [comment]
Just missing kmeta changes (after it gets merged) and getting jailhouse to build and work with 6.1 (u-boot is already updated).

**Review by quaresmajose — APPROVED** [review]
LGTM, I will do quick boot test it in my board

**Comment by quaresmajose** [comment]
looks like the kernel started well however we have `ERROR: reserving fdt memory region failed (addr=ff700000 size=8ca000 flags=4)` on u-boot.

```
U-Boot 2023.04-gd6bccb1b9e (Jun 09 2023 - 06:25:21 +0000)

SoC:   AM62X SR1.0 GP
Model: Texas Instruments AM625 SK
EEPROM not available at 80, trying to read at 81
Board: AM62-SKEVM rev E3
DRAM:  2 GiB
Core:  66 devices, 28 uclasses, devicetree: separate
MMC:   mmc@fa10000: 0, mmc@fa00000: 1
Loading Environment from FAT... Unable to read "uboot.env" from mmc1:1... 
In:    serial@2800000
Out:   serial@2800000
Err:   serial@2800000
Net:   eth0: ethernet@8000000port@1
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc1 is current device
3287 bytes read in 16 ms (200.2 KiB/s)
## Executing script at 82000000
sha256+ Saving Environment to FAT... OK
481 bytes read in 18 ms (25.4 KiB/s)
15839148 bytes read in 187 ms (80.8 MiB/s)
name_fit_config=conf-ti_k3-am625-sk.dtb
## Loading kernel from FIT Image at 90000000 ...
   Using 'conf-ti_k3-am625-sk.dtb' configuration
   Trying 'kernel-1' kernel subimage
     Description:  Linux kernel
     Type:         Kernel Image
     Compression:  gzip compressed
     Data Start:   0x9000010c
     Data Size:    9018451 Bytes = 8.6 MiB
     Architecture: AArch64
     OS:           Linux
     Load Address: 0x82000000
     Entry Point:  0x82000000
     Hash algo:    sha256
     Hash value:   675ff1564e3b9b68c7e3103dac26dae048287dd4848ee2c83a16c26dcdcc9647
   Verifying Hash Integrity ... sha256+ OK
## Loading ramdisk from FIT Image at 90000000 ...
   Using 'conf-ti_k3-am625-sk.dtb' configuration
   Trying 'ramdisk-1' ramdisk subimage
     Description:  initramfs-ostree-lmp-image-am62xx-evm
     Type:         RAMDisk Image
     Compression:  uncompressed
     Data Start:   0x908a5cf0
     Data Size:    6769944 Bytes = 6.5 MiB
     Architecture: AArch64
     OS:           Linux
     Load Address: 0x84000000
     Entry Point:  0x84000000
     Hash algo:    sha256
     Hash value:   198d0d92a42bdfd47dbcccdd6ea10bfd2289a446cd007c2feb72ffd8acd92be8
   Verifying Hash Integrity ... sha256+ OK
   Loading ramdisk from 0x908a5cf0 to 0x84000000
## Loading fdt from FIT Image at 90000000 ...
   Using 'conf-ti_k3-am625-sk.dtb' configuration
   Trying 'fdt-ti_k3-am625-sk.dtb' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x90899e74
     Data Size:    48524 Bytes = 47.4 KiB
     Architecture: AArch64
     Load Address: 0x88000000
     Hash algo:    sha256
     Hash value:   3c105b6e70b39762468fb605b351a654be0f82c59ffd3e3c14f0056a20aaa8ae
   Verifying Hash Integrity ... sha256+ OK
   Loading fdt from 0x90899e74 to 0x88000000
   Booting using the fdt blob at 0x88000000
Working FDT set to 88000000
   Uncompressing Kernel Image
   Loading Ramdisk to 8f98b000, end 8ffffd18 ... OK
ERROR: reserving fdt memory region failed (addr=ff700000 size=8ca000 flags=4)
   Loading Device Tree to 000000008f97c000, end 000000008f98ad8b ... OK
Working FDT set to 8f97c000

Starting kernel ...
```

**Comment by ricardosalveti** [comment]
Jailhouse support fixed on both u-boot and kernel.

**Pull request merged**
