### PR TITLE
Changes for kirkstone

### PR DESCRIPTION
**Pull request by ricardosalveti**
Set of changes for making meta-lmp compatible with kirkstone.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
@angolini @quaresmajose just a version bump atm but will push additional changes tomorrow before getting it ready for review.

**Comment by ricardosalveti** [comment]
Tested with intel-corei7-64 / qemu.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by quaresmajose — APPROVED** [review]
lgtm

**Review by Tim-Anderson — APPROVED** [review]
needs a PR description I think but otherwise LGTM

**Pull request merged**
