### PR TITLE
main: fix flashing open boards with -sec images

### PR DESCRIPTION
**Pull request by MrCry0**
Affected:

- apalis-imx6-sec
- apalis-im8-sec
- imx8mm-lpddr4-evk-sec

### CODE REVIEW

**Comment by ricardosalveti** [comment]
I don't mind being able to flash -sec images on open boards, but it is not really expected to work right due the other build specific changes we have in place.

Is this just to validate the flashing process?

**Comment by MrCry0** [comment]
> I don't mind being able to flash -sec images on open boards, but it is not really expected to work right due the other build specific changes we have in place.
> 
> Is this just to validate the flashing process?

Sure. It's for development/testing purposes. As a minimum, we can test the full image between fusing and closing.

**Comment by ricardosalveti** [comment]
Needs rebase.

**Comment by MrCry0** [comment]
> Needs rebase.

@ricardosalveti done

**Review by vanmaegima — APPROVED** [review]
LGTM

**Comment by MrCry0** [comment]
@vanmaegima @ricardosalveti updated: fixed the case when imx_is_closed() not enabled.

**Review by angolini — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
