### PR TITLE
LmP: move INHERIT out of distro config

### PR DESCRIPTION
**Pull request by quaresmajose**
**Archiver**
A fix to don't re-run the rm_work is merged upstream
https://git.yoctoproject.org/poky/commit/?id=6cd9a85d2b9f6272c0b0e9d68c6dbd5e8c0c336b
https://git.yoctoproject.org/poky/commit/?id=0f9773ee717d54ce1ed5001bc5ef4ec470f13476

**Create-spdx**
The create-spdx is been moved to only runs on CI as local builds can run in the majority of time without this
that reduces the build time.

**Buildhistory**
Moves the buildhistory to bitbake conf as this is not a distro
configuration and is more related to a build configuration.

### CODE REVIEW

**Comment by quaresmajose** [comment]
Merged upstream on master branch:

- sstatesig: skip the rm_work task signature
https://git.yoctoproject.org/poky/commit/?id=6cd9a85d2b9f6272c0b0e9d68c6dbd5e8c0c336b

- rm_work: exclude the SSTATETASKS from the rm_work tasks sinature
https://git.yoctoproject.org/poky/commit/?id=0f9773ee717d54ce1ed5001bc5ef4ec470f13476

**Comment by quaresmajose** [comment]
We don't need to wait for this patch to be merged on Kirstone, this is only build improvements and don't affect the target so we can merge it.

**Review by MrCry0 — APPROVED** [review]
LGTM (not tested)

**Comment by quaresmajose** [comment]
Added to more commits for this PR where all of them is to disable some inherit  that will be enabled else were

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
