### PR TITLE
bsp: meta-freescale: Convert to the new override subsystem

### PR DESCRIPTION
**Pull request by ricardosalveti**
[1] updated the override subsystem used in meta-freescale, and now it includes
the BSP, with 3 options:

  imx*-generic-bsp
  imx*-nxp-bsp
  imx*-mainline-bsp

Generic options (machine specific, not BSP) were updated to
imx-generic-bsp, while options specific to the NXP BSP (e.g. kernel,
wireless driver, etc) were updated to use the respective imx*-nxp-bsp
overrides.

[1] https://github.com/Freescale/meta-freescale/commit/30f5ce1d2168389295b4813e01898c2fb0f9bab9

Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Basically the imx override was split into imx-generic-bsp (applied to both upstream and nxp bsp), imx-nxp-bsp (specific to the nxp bsp) and imx-mainline-bsp (specific to the upstream bsp).

**Comment by ricardosalveti** [comment]
lmp-manifest test job/pr created at https://github.com/foundriesio/lmp-manifest/pull/189.

**Comment by ricardosalveti** [comment]
imx builds are finally all green with these changes.

**Comment by quaresmajose** [comment]
> LmP has been using imx*-nxp-bsp, so use it as the default target
in the conversion.

but the there are many imx*-generic-bsp override in this patch

**Comment by ricardosalveti** [comment]
@quaresmajose you are correct, it was initially aligned with nxp-bsp only but I updated to leverage generic as well, let me update the commit message.

**Comment by ricardosalveti** [comment]
@quaresmajose updated.

**Review by quaresmajose — APPROVED** [review]
LGTM

**Pull request merged**
