### PR TITLE
Update additional MX8 targets to the latest NXP BSP

### PR DESCRIPTION
**Pull request by ricardosalveti**
CI runs: https://github.com/foundriesio/lmp-manifest/pull/258

Validation:

- [x] mx8mp
   - [x] build tested
   - [x] normal test run
   - [x] ebbr test run
   - [x] base test run
   - [x] sec test run 
   - [x] mfgtools
- [x] mx8mn
   - [x] build tested
   - [x] normal test run
   - [x] base test run
   - [x] sec test run 
   - [x] mfgtools
- [ ] mx8qm
   - [x] build tested
   - [ ] normal test run
   - [ ] base test run
   - [ ] sec test run 
   - [ ] mfgtools
- [ ] apalis-imx8
   - [x] build tested
   - [ ] normal test run
   - [ ] base test run
   - [ ] mfgtools

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Matching CI build at https://github.com/foundriesio/lmp-manifest/pull/258.

@vanmaegima @Tim-Anderson can you give a hand to validate the builds on 8mn and 8mp? I don't have either locally. Thanks!

**Comment by MrCry0** [comment]
@ricardosalveti 
mx8mp:
- [ ] flash with mfgtool image (build #1888)
- [ ] normal boot (build #1888)

**Comment by vanmaegima** [comment]
mx8mn:

- [ ] boot -sec
- [ ] boot normal (on closed board)
- [ ] mfgtool test

**Comment by ricardosalveti** [comment]
Updated build available at https://ci.foundries.io/projects/lmp/builds/1893/

**Comment by vanmaegima** [comment]
error with imx8mn base:

> U-Boot SPL 2022.04+fio+g92012fed80 (Nov 10 2022 - 16:25:08 +0000)            
> ### ERROR ### Please RESET the board ###

**Comment by vanmaegima** [comment]
- [ ] imx8mn base 
- [ ] imx8mp base

**Comment by ricardosalveti** [comment]
Since most targets are now working (pending apalis-imx8/u-boot), will merge so we can work on the remaining issues on top of a single manifest.

**Pull request merged**
