### PR TITLE
base: lmp-staging: add an handler to warn about 'do_deploy' bad usage

### PR DESCRIPTION
**Pull request by quaresmajose**
This handler will warn when there are 'do_deploy' dependencies without setting the DEPENDS.
One of the side effect of this issues is SPDX documents not including the correct dependencies.

```
/
| WARNING: lmp-boot-firmware-0-r0 do_install: Task 'do_install' depends on 'virtual/bootloader:do_deploy' but 'virtual/bootloader' is not in DEPENDS
| WARNING: lmp-boot-firmware-0-r0 do_install: Task 'do_install' depends on 'virtual/trusted-firmware-a:do_deploy' but 'virtual/trusted-firmware-a' is not in DEPENDS
\
```

### CODE REVIEW

**Comment by quaresmajose** [comment]
Maybe this can be proposed upstream be on the `meta/classes/create-spdx.bbclass`

**Review by MrCry0 — APPROVED** [review]
Cool. LGTM

**Comment by ricardosalveti** [comment]
`WARNING: lmp-base-console-image-1.0-r0 do_image_ostree: Task 'do_image_ostree' depends on 'virtual/kernel:do_deploy' but 'virtual/kernel' is not in DEPENDS`

Shouldn't be an issue for image related tasks.

**Comment by quaresmajose** [comment]
> `WARNING: lmp-base-console-image-1.0-r0 do_image_ostree: Task 'do_image_ostree' depends on 'virtual/kernel:do_deploy' but 'virtual/kernel' is not in DEPENDS`
> 
> Shouldn't be an issue for image related tasks.

On the PR https://github.com/foundriesio/meta-lmp/pull/1109 I am testing I have this already fixed.
This one has one variable with the exceptions to be spiked, the default value is to skip the check in the images.

I will close this one as https://github.com/foundriesio/meta-lmp/pull/1109 also has the fixes and is better have it all together.

**Pull request closed without merging**
