### PR TITLE
Add support for lmp-boot-firmware (boot firmware updates via OTA)

### PR DESCRIPTION
**Pull request by ricardosalveti**
Add lmp-boot-firmware recipe and configure the same targets as set by https://github.com/foundriesio/meta-lmp/pull/312 to allow performing boot firmware updates via OTA.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Can be used by defining the boot firmware files via the LMP_BOOT_FIRMWARE_FILES variable.

```
diff --git a/meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc b/meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
index 467db9e..ee30e3a 100644
--- a/meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
+++ b/meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
@@ -231,6 +231,7 @@ UBOOT_ENTRYPOINT_mx6ull  = "0x80008000"
 UBOOT_DTB_LOADADDRESS_mx6ull = "0x85800000"
 UBOOT_RD_LOADADDRESS_mx6ull = "0x84000000"
 MACHINE_FEATURES_append_mx6ull = " optee"
+LMP_BOOT_FIRMWARE_FILES_mx6ull = "SPL u-boot.itb"
 IMAGE_BOOT_FILES_sota_mx6ull = " boot.itb SPL u-boot.itb "
 IMAGE_BOOT_FILES_mx6ull = " boot.scr uEnv.txt zImage"
 KERNEL_IMAGETYPE_sota_mx6ull = "fitImage"
```

Another option is to create a bbappend and provide the signed binaries via SRC_URI (in addition to LMP_BOOT_FIRMWARE_FILES) and device PV for version.txt.

Don't forget to include such recipe in the target image (e.g. lmp-factory-image).

**Comment by angolini** [comment]
What exactly is "firmware boot files"? Any file I could want to install at `${D}${nonarch_base_libdir}/firmware/`?

**Comment by ricardosalveti** [comment]
> What exactly is "firmware boot files"? Any file I could want to install at `${D}${nonarch_base_libdir}/firmware/`?

From this recipe it could be any file that gets deployed in deploy dir, but the original scope would be for files such as SPL, u-boot.itb and so on, to be used with https://github.com/foundriesio/meta-lmp/pull/312/files.

We need this recipe because the signed u-boot itb is only deployed and not installed or made available as a package, so the only way to get it available in the rootfs is by packaging it. Once in the rootfs we can get the boot script to update the required firmware during boot.

**Comment by igoropaniuk** [comment]
@ricardosalveti at I understand it's just more sophisticated version of the script that I had in meta-sub rep.
Is it possible to extend it so we automatically copy boot images from imx-mkimage and u-boot-fio if the board is not closed?

**Comment by ricardosalveti** [comment]
@igoropaniuk this should hopefully be enough, testing on my factory now with your pr.

**Review by igoropaniuk — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
Will merge so we can do a bit more testing on this.

**Pull request merged**
