### PR TITLE
AM6XXX: publish boot firmware files

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Opening as a draft because this set is causing a huge amount of spdx errors (the usual removal before they are created). I believe this is because of the do_deploy dependencies at lmp-boot-firmware, which causes the dependency chain to have a different order, presenting the issue.

@quaresmajose another one for you to investigate as you are playing with a possible fix there.

**Comment by quaresmajose** [comment]
This is another proof that the spdx issue is related with the do_deploy task, hope I can fix it shortly.

**Comment by quaresmajose** [comment]
@ricardosalveti maybe this can now be rebased and merged.

**Review by quaresmajose — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request merged**
