### PR TITLE
Versal

### PR DESCRIPTION
**Pull request by ldts**

### CODE REVIEW

**Comment by ldts** [comment]
still need to do the kernel config changes to enable the performance governor instead of the on-demand

**Comment by ricardosalveti** [comment]
> @rsalveti kernel config changes to enable the performance governor
> 
> [foundriesio/lmp-kernel-cache#49](https://github.com/foundriesio/lmp-kernel-cache/pull/49)

merged, please do a bump.

**Comment by ldts** [comment]
holdon

**Comment by ldts** [comment]
pushed the wrong commit for the branch

**Comment by ldts** [comment]
should be ok now

**Comment by ricardosalveti** [comment]
Please add the changelog to the kmeta bump, as done for every change to that file.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
