### PR TITLE
lmp.inc: set default username/password variables

### PR DESCRIPTION
**Pull request by mike-scott**
These can be overriden in local.conf

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
I changed the default from "osf" -> "fio" here.    Maybe I should keep "osf" for now?  Or should I also put up documentation changes?

**Comment by mike-scott** [comment]
Btw, still testing this.

**Comment by doanac** [comment]
i like the idea of "fio" but documentation and CI depend of "osf". We just need to be careful about doing this

**Comment by mike-scott** [comment]
@doanac yep, put the user/pwd back to "osf" by default to avoid any complications.

**Comment by mike-scott** [comment]
This can wait for @ricardosalveti to look at.  It's not critical.

**Pull request merged**
