### PR TITLE
ebbr-nxp: add wi-fi firmware for imx8mm evkb #483

### PR DESCRIPTION
**Pull request by MrCry0**
Can be merged separately. Wi-Fi starts working after merging https://github.com/foundriesio/lmp-kernel-cache/pull/24

### CODE REVIEW

**Review by vanmaegima — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
I wonder if we should instead just import https://source.codeaurora.org/external/imx/meta-imx/tree/meta-bsp/recipes-kernel/linux-firmware/linux-firmware_%25.bbappend?h=hardknott-5.10.52-2.1.0, which seems to be adding all the relevant missing firmware.

Since this might not necessarily apply to every machine, we can make the appends be specific to imx if needed.

**Comment by MrCry0** [comment]
> I wonder if we should instead just import https://source.codeaurora.org/external/imx/meta-imx/tree/meta-bsp/recipes-kernel/linux-firmware/linux-firmware_%25.bbappend?h=hardknott-5.10.52-2.1.0

@ricardosalveti 
But HOW? :) I've been searching for hours for that firmware's recipe through all imx repos and the whole Google :)
Well, so now it is better to use that recipe, keep an original firmware name, and add a kernel patch to alternate a firmware name in a mwifiex driver.
Do you mind?

**Comment by ricardosalveti** [comment]
We can copy paste that recipe and just make the append specific to imx (imx is a generic override for all imx machines), simply to avoid replacing firmware files that could break other machines.

But if the files are not replacing anything, we should be ok to have it as done at the current recipe.

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Pull request closed without merging**
