### PR TITLE
bsp: optee-os-fio: apalis-imx6: disable caam crypto driver

### PR DESCRIPTION
**Pull request by ricardosalveti**
When enabled it hangs the device as it gets used (e.g. xtest).

Temporarily disable to unblock apalis-imx6, until the actual issue gets investigated, as CAAM should be supported at imx6q (and useful to provide hw rng).

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

### CODE REVIEW

**Comment by ricardosalveti** [comment]
On apalis-imx6 1gb and 2gb, open boards:

```
+-----------------------------------------------------
29844 subtests of which 0 failed
123 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by ricardosalveti** [comment]
Building https://github.com/foundriesio/lmp-manifest/pull/225 to build for all apalis-imx6 variants.

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by vanmaegima — APPROVED** [review]
Tested on 3.15.

**Pull request merged**
