### PR TITLE
base: pkcs11-se05-import: update to APDU version

### PR DESCRIPTION
**Pull request by ldts**
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by ldts** [comment]
I havent tested it in LmP -only standalone

**Comment by ldts** [comment]
@vanmaegima this is what I had in mind

**Comment by ricardosalveti** [comment]
Mind adding the reason for the switch as part of the commit message?

**Review by MrCry0 — APPROVED** [review]
With Ricardo's note, LGTM.

**Comment by ldts** [comment]
https://github.com/foundriesio/meta-lmp/pull/876

**Pull request closed without merging**
