### PR TITLE
General fixes for latest meta-freescale

### PR DESCRIPTION
**Pull request by ricardosalveti**
Main change is the imx-atf update (from 2.4 to 2.6).

@igoropaniuk mind reviewing the patches and the 2.6 base revision? A few of your patches were already applied with minor changes, so a more complete review would be good to make sure everything is there.

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by quaresmajose — APPROVED** [review]
LGTM

**Review by igoropaniuk — APPROVED** [review]
LGTM

**Comment by quaresmajose** [comment]
There are some issues with this patch on main-next
```
ERROR: imx-atf-2.6+gitAUTOINC+c6a19b1a35-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/srv/oe/layers/openembedded-core/scripts:/srv/oe/build/tmp-lmp/work/apalis_imx8_sec-lmp-linux/imx-atf/2.6+gitAUTOINC+c6a19b1a35-r0/recipe-sysroot-native/usr/bin/aarch64-lmp-linux:/srv/oe/build/tmp-lmp/work/apalis_imx8_sec-lmp-linux/imx-atf/2.6+gitAUTOINC+c6a19b1a35-r0/recipe-sysroot/usr/bin/crossscripts:/srv/oe/build/tmp-lmp/work/apalis_imx8_sec-lmp-linux/imx-atf/2.6+gitAUTOINC+c6a19b1a35-r0/recipe-sysroot-native/usr/sbin:/srv/oe/build/tmp-lmp/work/apalis_imx8_sec-lmp-linux/imx-atf/2.6+gitAUTOINC+c6a19b1a35-r0/recipe-sysroot-native/usr/bin:/srv/oe/build/tmp-lmp/work/apalis_imx8_sec-lmp-linux/imx-atf/2.6+gitAUTOINC+c6a19b1a35-r0/recipe-sysroot-native/sbin:/srv/oe/build/tmp-lmp/work/apalis_imx8_sec-lmp-linux/imx-atf/2.6+gitAUTOINC+c6a19b1a35-r0/recipe-sysroot-native/bin:/srv/oe/bitbake/bin:/srv/oe/build/tmp-lmp/hosttools"; export HOME="/home/builder"; LANG=C git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false -c core.pager=cat fetch -f --progress /srv/oe/downloads/tmpbowqc9mz  failed with exit code 128, output:
fatal: Couldn't find remote ref HEAD
fatal: the remote end hung up unexpectedly

ERROR: imx-atf-2.6+gitAUTOINC+c6a19b1a35-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://source.codeaurora.org/external/imx/imx-atf.git;protocol=https;branch=lf_v2.6')
ERROR: Logfile of failure stored in: /srv/oe/build/tmp-lmp/work/apalis_imx8_sec-lmp-linux/imx-atf/2.6+gitAUTOINC+c6a19b1a35-r0/temp/log.do_fetch.155809
```

**Pull request merged**
