### PR TITLE
[backporting] Update RPI kernel linux-lmp-rpi to 5.15

### PR DESCRIPTION
**Pull request by quaresmajose**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Usually there is a need to match the rpi firmware with the kernel version used as well, so something we might want to review as well.

**Comment by quaresmajose** [comment]
> Usually there is a need to match the rpi firmware with the kernel version used as well, so something we might want to review as well.

I will take a look the other pieces, Thanks for pointing that.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
