### PR TITLE
Bump fio docker fsck

### PR DESCRIPTION
**Pull request by mike-sul**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Please have both in a single commit, otherwise the build will fail with just the first patch applied.

**Comment by mike-sul** [comment]
> Please have both in a single commit, otherwise the build will fail with just the first patch applied.

done.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by quaresmajose — APPROVED** [review]

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
